// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-metrics-powerstore/internal/service (interfaces: PowerStoreClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/powerstore_client_mocks.go -package=mocks github.com/dell/csm-metrics-powerstore/internal/service PowerStoreClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gopowerstore "github.com/dell/gopowerstore"
	gomock "go.uber.org/mock/gomock"
)

// MockPowerStoreClient is a mock of PowerStoreClient interface.
type MockPowerStoreClient struct {
	ctrl     *gomock.Controller
	recorder *MockPowerStoreClientMockRecorder
	isgomock struct{}
}

// MockPowerStoreClientMockRecorder is the mock recorder for MockPowerStoreClient.
type MockPowerStoreClientMockRecorder struct {
	mock *MockPowerStoreClient
}

// NewMockPowerStoreClient creates a new mock instance.
func NewMockPowerStoreClient(ctrl *gomock.Controller) *MockPowerStoreClient {
	mock := &MockPowerStoreClient{ctrl: ctrl}
	mock.recorder = &MockPowerStoreClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPowerStoreClient) EXPECT() *MockPowerStoreClientMockRecorder {
	return m.recorder
}

// FileSystemMirrorTransferRate mocks base method.
func (m *MockPowerStoreClient) FileSystemMirrorTransferRate(ctx context.Context, id string) ([]gopowerstore.VolumeMirrorTransferRateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSystemMirrorTransferRate", ctx, id)
	ret0, _ := ret[0].([]gopowerstore.VolumeMirrorTransferRateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileSystemMirrorTransferRate indicates an expected call of FileSystemMirrorTransferRate.
func (mr *MockPowerStoreClientMockRecorder) FileSystemMirrorTransferRate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSystemMirrorTransferRate", reflect.TypeOf((*MockPowerStoreClient)(nil).FileSystemMirrorTransferRate), ctx, id)
}

// GetProtectionPolicies mocks base method.
func (m *MockPowerStoreClient) GetProtectionPolicies(ctx context.Context) ([]gopowerstore.ProtectionPolicy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProtectionPolicies", ctx)
	ret0, _ := ret[0].([]gopowerstore.ProtectionPolicy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProtectionPolicies indicates an expected call of GetProtectionPolicies.
func (mr *MockPowerStoreClientMockRecorder) GetProtectionPolicies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtectionPolicies", reflect.TypeOf((*MockPowerStoreClient)(nil).GetProtectionPolicies), ctx)
}

// GetFS mocks base method.
func (m *MockPowerStoreClient) GetFS(arg0 context.Context, arg1 string) (gopowerstore.FileSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFS", arg0, arg1)
	ret0, _ := ret[0].(gopowerstore.FileSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFS indicates an expected call of GetFS.
func (mr *MockPowerStoreClientMockRecorder) GetFS(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFS", reflect.TypeOf((*MockPowerStoreClient)(nil).GetFS), arg0, arg1)
}

// PerformanceMetricsByFileSystem mocks base method.
func (m *MockPowerStoreClient) PerformanceMetricsByFileSystem(arg0 context.Context, arg1 string, arg2 gopowerstore.MetricsIntervalEnum) ([]gopowerstore.PerformanceMetricsByFileSystemResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformanceMetricsByFileSystem", arg0, arg1, arg2)
	ret0, _ := ret[0].([]gopowerstore.PerformanceMetricsByFileSystemResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PerformanceMetricsByFileSystem indicates an expected call of PerformanceMetricsByFileSystem.
func (mr *MockPowerStoreClientMockRecorder) PerformanceMetricsByFileSystem(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformanceMetricsByFileSystem", reflect.TypeOf((*MockPowerStoreClient)(nil).PerformanceMetricsByFileSystem), arg0, arg1, arg2)
}

// PerformanceMetricsByVolume mocks base method.
func (m *MockPowerStoreClient) PerformanceMetricsByVolume(arg0 context.Context, arg1 string, arg2 gopowerstore.MetricsIntervalEnum) ([]gopowerstore.PerformanceMetricsByVolumeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformanceMetricsByVolume", arg0, arg1, arg2)
	ret0, _ := ret[0].([]gopowerstore.PerformanceMetricsByVolumeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PerformanceMetricsByVolume indicates an expected call of PerformanceMetricsByVolume.
func (mr *MockPowerStoreClientMockRecorder) PerformanceMetricsByVolume(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformanceMetricsByVolume", reflect.TypeOf((*MockPowerStoreClient)(nil).PerformanceMetricsByVolume), arg0, arg1, arg2)
}

// SpaceMetricsByVolume mocks base method.
func (m *MockPowerStoreClient) SpaceMetricsByVolume(arg0 context.Context, arg1 string, arg2 gopowerstore.MetricsIntervalEnum) ([]gopowerstore.SpaceMetricsByVolumeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpaceMetricsByVolume", arg0, arg1, arg2)
	ret0, _ := ret[0].([]gopowerstore.SpaceMetricsByVolumeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SpaceMetricsByVolume indicates an expected call of SpaceMetricsByVolume.
func (mr *MockPowerStoreClientMockRecorder) SpaceMetricsByVolume(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpaceMetricsByVolume", reflect.TypeOf((*MockPowerStoreClient)(nil).SpaceMetricsByVolume), arg0, arg1, arg2)
}

// VolumeMirrorTransferRate mocks base method.
func (m *MockPowerStoreClient) VolumeMirrorTransferRate(ctx context.Context, id string) ([]gopowerstore.VolumeMirrorTransferRateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VolumeMirrorTransferRate", ctx, id)
	ret0, _ := ret[0].([]gopowerstore.VolumeMirrorTransferRateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VolumeMirrorTransferRate indicates an expected call of VolumeMirrorTransferRate.
func (mr *MockPowerStoreClientMockRecorder) VolumeMirrorTransferRate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VolumeMirrorTransferRate", reflect.TypeOf((*MockPowerStoreClient)(nil).VolumeMirrorTransferRate), ctx, id)
}
